# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25dad5a72c5362944dd2796fc42f229f4063eca940200ec46c706c850979ee98e14a2b3e0eeabf491d5eb85e84528c863759f48da8604aa1c20ffdc9586d529e

test:
  secret_key_base: 00a18f77758219ec0c4e0a404d479bb2982ea051a9e5888049730aa3e6fe68c1f4d90ef8116f590d4abbc5a36e7c1a4adbec2a83438e7f0a208495e8de745014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
